# Site settings
title: Eirini Ntoutsi
email: ntoutsi@dbs.ifi.lmu.de 
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://dmgroup.github.io" # the base hostname & protocol for your site
github_username:  abelsiqueira
permalink: /:title/

# Build settings
markdown: kramdown
highlight: rouge
plugins:
  - jekyll-seo-tag
